Save bug-reporters some time
zed-industries/feedback pull request #98
Opened 2022-06-20 11:25 UTC by exalted

2022-06-21 06:55 UTC, as-cii requested changes
Thanks for the pull request! I left a small suggestion to make the script slightly easier to parse at a first glance, but otherwise this looks pretty nice! ⚡

2022-06-21 06:55 UTC, as-cii commented on .github/ISSUE_TEMPLATE/bug_report.md
> +echo -e "- Architecture: \`$(uname -m)\`\n- $(sw_vers -productName) Version: \`$(sw_vers -productVersion) ($(sw_vers -buildVersion))\`\n- Zed Version: \`$(/Applications/Zed.app/Contents/MacOS/cli --v
What do you think about removing the trailing `grep` invocation? It will include the installation path but would also makes the script a bit simpler (and easier to skim before copy-pasting it into one's terminal). 💭

2022-06-22 07:54 UTC, exalted commented on .github/ISSUE_TEMPLATE/bug_report.md
> +echo -e "- Architecture: \`$(uname -m)\`\n- $(sw_vers -productName) Version: \`$(sw_vers -productVersion) ($(sw_vers -buildVersion))\`\n- Zed Version: \`$(/Applications/Zed.app/Contents/MacOS/cli --v
You got it! https://github.com/zed-industries/feedback/pull/98/commits/f573a90e43f7db67fbfe32d52aee2d898a4a083e

2022-06-22 07:56 UTC, as-cii commented
Lovely.

2022-06-22 07:56 UTC, merged